name: Python Backend Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64
    - run: pip install nox==2019.11.9
    - run: pip install poetry==1.0.5
    - run: cd backend || return && nox
